// jshint esversion:6

const mongoose = require('mongoose');

const orderSchema = new mongoose.Schema({
  shippingInfo:{
    address:{
      type:String,
      required:true,
    },
    city:{
      type:String,
      required:true,
    },
    pincode:{
      type:String,
      required:true,
    },
    country:{
      type:String,
      required:true,
    },
    phoneNum:{
      type:String,
      required:true
    }
  },
  user:{
    type:mongoose.Schema.Types.ObjectId,
    required:true,
    ref:"User"
  },
  orderItems:[{
    name:{
      type:String,
      required:true,
    },
    quantity:{
      type:Number,
      required:true,
    },
    image:{
      type:String,
      required:true,
    },
    price:{
      type:Number,
      required:true,
    },
    product:{
      type:mongoose.Schema.Types.ObjectId,
      required:true,
      ref:"Product"
    },
  }],
  paymnetInfo:{
    id:{
      type:String
    },
    status:{
      type:String
    }
  },
  paidAt:{
    type:Date
  },
  itemsPriceTotal:{
    type:Number,
    required:true,
    defaukt:0.0
  },
  shippingPrice:{
    type:Number,
    required:true,
    defaukt:0.0
  },
  totalPrice:{
    type:Number,
    required:true,
    defaukt:0.0
  },
  shippingStatus:{
    type:String,
    required:true,
    default:"Processing"
  },
  deliveredAt:{
    type:Date
  }
});

module.exports= mongoose.model("Order",orderSchema);
